package:
    type:           yii2-extension
    name:           hipanel-site
    title:          Selling site for HiPanel
    headline:       HiPanel Site
    homepage:       http://hipanel.com/
    keywords:       hipanel, site
    namespace:      hipanel\site
    description:    |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is next generation control panel for hosting, domains and more.

        This package is the selling site for HiPanel.
